"""Tests for AsyncTTLCache — generated by SAGE-PRO Red-Team Ensemble."""
import asyncio
import time
import threading
import pytest

from lru_async import AsyncTTLCache


class TestBasicOperations:
    def test_put_and_get(self):
        cache = AsyncTTLCache(maxsize=8)
        cache.put("a", 1)
        assert cache.get("a") == 1

    def test_missing_key_returns_none(self):
        cache = AsyncTTLCache()
        assert cache.get("nonexistent") is None

    def test_lru_eviction(self):
        cache = AsyncTTLCache(maxsize=2)
        cache.put("a", 1)
        cache.put("b", 2)
        cache.put("c", 3)  # evicts "a"
        assert cache.get("a") is None
        assert cache.get("b") == 2

    def test_update_moves_to_end(self):
        cache = AsyncTTLCache(maxsize=2)
        cache.put("a", 1)
        cache.put("b", 2)
        cache.put("a", 10)   # refresh "a"
        cache.put("c", 3)    # evicts "b" (oldest)
        assert cache.get("a") == 10
        assert cache.get("b") is None


class TestTTLExpiry:
    def test_expired_key_returns_none(self):
        cache = AsyncTTLCache(default_ttl=0.05)
        cache.put("x", 42)
        time.sleep(0.1)
        assert cache.get("x") is None

    def test_custom_ttl(self):
        cache = AsyncTTLCache(default_ttl=10.0)
        cache.put("short", 1, ttl=0.05)
        time.sleep(0.1)
        assert cache.get("short") is None


class TestThreadSafety:
    def test_concurrent_writes(self):
        cache = AsyncTTLCache(maxsize=1000)
        errors = []

        def writer(prefix: str):
            try:
                for i in range(200):
                    cache.put(f"{prefix}_{i}", i)
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=writer, args=(f"t{t}",)) for t in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert not errors
        assert cache.size <= 1000


class TestAsyncEviction:
    @pytest.mark.asyncio
    async def test_background_eviction(self):
        cache = AsyncTTLCache(maxsize=100, default_ttl=0.05, eviction_interval=0.1)
        cache.put("die", 1)
        await cache.start_eviction()
        await asyncio.sleep(0.3)
        assert cache.get("die") is None
        await cache.stop_eviction()
